### ISSUE TITLE
next auth set to false in env wont work.

### ISSUE THREAD

**Issue by Bwaite43** [dotneet/smart-chatbot-ui#129]
not sure what im doing wrong but I set the NEXTAUTH_ENABLED=false it gives me this.

[next-auth][error][NO_SECRET]
https://next-auth.js.org/errors#no_secret
[next-auth][error][NO_SECRET]
https://next-auth.js.org/errors#no_secret Please define a `secret` in production. MissingSecret [MissingSecretError]: Please define a `secret` in production.
    at assertConfig (/app/node_modules/next-auth/core/lib/assert.js:42:12)
    at AuthHandler (/app/node_modules/next-auth/core/index.js:77:52)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NextAuthApiHandler (/app/node_modules/next-auth/next/index.js:22:19)
    at async NextAuth._args$ (/app/node_modules/next-auth/next/index.js:106:14) {
  code: 'NO_SECRET'

----

# NextAuth
NEXTAUTH_ENABLED=false
#NEXTAUTH_EMAIL_PATTERN=.+@example.com
#NEXTAUTH_URL=http://localhost:3000
# must replace if you use NextAuth
#NEXTAUTH_SECRET=
#GITHUB_CLIENT_ID=
#GITHUB_CLIENT_SECRET=
#GOOGLE_CLIENT_ID=
#GOOGLE_CLIENT_SECRET=
#COGNITO_CLIENT_ID=
#COGNITO_CLIENT_SECRET=
#COGNITO_ISSUER=

**Comment by makeneko** [comment]
Commenting out NEXTAUTH_SECRET doesn't seem to work; setting the value of dummy seems to be a good idea.
